### ISSUE TITLE
Rebuild the site infrastructure

### ISSUE THREAD

**Issue by ndw** [markupdeclaration/markupdeclaration.org#27]
Using Jekyll was both convenient and simple. And it does have some nice features in terms of ease of publication. However, it's a mess from a markup perspective, which seems a little counter-productive for this project.

I propose to rebuild the site using Gradle as the driving build technology. It's well established so there's likely to be other members of the community that know about it, it's JVM based so it's cross-platform, and it's commonly available in CI environments.

Goals:

1. The source files for pages in the website should be in markup (I propose HTML, or Markdown, or DocBook to start. DocBook is probably overkill, but it will demonstrate using XML.)
2. The organization of the source documents should have an obvious correspondence to the organization of the published pages.
3. We must preserve automated publication through PRs, with appropriate validation

**Comment by btusdin** [comment]
Since I know none of these site generation tools one is as mysterious as another to me. I will endeavor to learn what ever infrastructure you select - and consider the challenge a side benefit of playing this game. 

— Tommie

> On Oct 22, 2018, at 6:24 PM, Norman Walsh <notifications@github.com> wrote:
> 
> Using Jekyll was both convenient and simple. And it does have some nice features in terms of ease of publication. However, it's a mess from a markup perspective, which seems a little counter-productive for this project.
> 
> I propose to rebuild the site using Gradle as the driving build technology. It's well established so there's likely to be other members of the community that know about it, it's JVM based so it's cross-platform, and it's commonly available in CI environments.
> 
> Goals:
> 
> 	• The source files for pages in the website should be in markup (I propose HTML, or Markdown, or DocBook to start. DocBook is probably overkill, but it will demonstrate using XML.)
> 	• The organization of the source documents should have an obvious correspondence to the organization of the published pages.
> 	• We must preserve automated publication through PRs, with appropriate validation
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

====================================================================== 
B. Tommie Usdin                        mailto:btusdin@mulberrytech.com
Mulberry Technologies, Inc.               https://www.mulberrytech.com
17 West Jefferson Street                           Phone: 301/315-9631 
Suite 207                                    Direct Line: 301/315-9634 
Rockville, MD  20850                                 Fax: 301/315-8285 
----------------------------------------------------------------------
Mulberry Technologies: A Consultancy Specializing in XML and SGML               
======================================================================

**Comment by ndw** [comment]
You shouldn't *have* to do anything but edit the pages and make PRs. If you want to run the system locally, you should be able to run "./gradlew website" and it should all just magically work. There's a lot of reason to be optimistic that this will be the case.

**Comment by ndw** [comment]
(It won't be the case, because these are computers, but I have boundless optimism.)

**Comment by ndw** [comment]
Much improved. New docs and updated README coming soon.

**Comment by ndw** [comment]
And by soon, I mean "in a couple of minutes."
